// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.31.1
// source: applewloc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WifiDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bssid         *string                `protobuf:"bytes,1,req,name=bssid" json:"bssid,omitempty"`
	Location      *WifiDevice_Location   `protobuf:"bytes,2,opt,name=location" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiDevice) Reset() {
	*x = WifiDevice{}
	mi := &file_applewloc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiDevice) ProtoMessage() {}

func (x *WifiDevice) ProtoReflect() protoreflect.Message {
	mi := &file_applewloc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiDevice.ProtoReflect.Descriptor instead.
func (*WifiDevice) Descriptor() ([]byte, []int) {
	return file_applewloc_proto_rawDescGZIP(), []int{0}
}

func (x *WifiDevice) GetBssid() string {
	if x != nil && x.Bssid != nil {
		return *x.Bssid
	}
	return ""
}

func (x *WifiDevice) GetLocation() *WifiDevice_Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type AppleWLoc struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WifiDevices        []*WifiDevice          `protobuf:"bytes,2,rep,name=wifi_devices,json=wifiDevices" json:"wifi_devices,omitempty"`
	UnknownValue1      *int32                 `protobuf:"varint,3,opt,name=unknown_value1,json=unknownValue1" json:"unknown_value1,omitempty"`
	ReturnSingleResult *int32                 `protobuf:"varint,4,opt,name=return_single_result,json=returnSingleResult" json:"return_single_result,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppleWLoc) Reset() {
	*x = AppleWLoc{}
	mi := &file_applewloc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppleWLoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppleWLoc) ProtoMessage() {}

func (x *AppleWLoc) ProtoReflect() protoreflect.Message {
	mi := &file_applewloc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppleWLoc.ProtoReflect.Descriptor instead.
func (*AppleWLoc) Descriptor() ([]byte, []int) {
	return file_applewloc_proto_rawDescGZIP(), []int{1}
}

func (x *AppleWLoc) GetWifiDevices() []*WifiDevice {
	if x != nil {
		return x.WifiDevices
	}
	return nil
}

func (x *AppleWLoc) GetUnknownValue1() int32 {
	if x != nil && x.UnknownValue1 != nil {
		return *x.UnknownValue1
	}
	return 0
}

func (x *AppleWLoc) GetReturnSingleResult() int32 {
	if x != nil && x.ReturnSingleResult != nil {
		return *x.ReturnSingleResult
	}
	return 0
}

type WifiDevice_Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *int64                 `protobuf:"varint,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     *int64                 `protobuf:"varint,2,opt,name=longitude" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WifiDevice_Location) Reset() {
	*x = WifiDevice_Location{}
	mi := &file_applewloc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WifiDevice_Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WifiDevice_Location) ProtoMessage() {}

func (x *WifiDevice_Location) ProtoReflect() protoreflect.Message {
	mi := &file_applewloc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WifiDevice_Location.ProtoReflect.Descriptor instead.
func (*WifiDevice_Location) Descriptor() ([]byte, []int) {
	return file_applewloc_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WifiDevice_Location) GetLatitude() int64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *WifiDevice_Location) GetLongitude() int64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

var File_applewloc_proto protoreflect.FileDescriptor

const file_applewloc_proto_rawDesc = "" +
	"\n" +
	"\x0fapplewloc.proto\x12\x04main\"\x9f\x01\n" +
	"\n" +
	"WifiDevice\x12\x14\n" +
	"\x05bssid\x18\x01 \x02(\tR\x05bssid\x125\n" +
	"\blocation\x18\x02 \x01(\v2\x19.main.WifiDevice.LocationR\blocation\x1aD\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x03R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x03R\tlongitude\"\x99\x01\n" +
	"\tAppleWLoc\x123\n" +
	"\fwifi_devices\x18\x02 \x03(\v2\x10.main.WifiDeviceR\vwifiDevices\x12%\n" +
	"\x0eunknown_value1\x18\x03 \x01(\x05R\runknownValue1\x120\n" +
	"\x14return_single_result\x18\x04 \x01(\x05R\x12returnSingleResultB\x06Z\x04./pb"

var (
	file_applewloc_proto_rawDescOnce sync.Once
	file_applewloc_proto_rawDescData []byte
)

func file_applewloc_proto_rawDescGZIP() []byte {
	file_applewloc_proto_rawDescOnce.Do(func() {
		file_applewloc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_applewloc_proto_rawDesc), len(file_applewloc_proto_rawDesc)))
	})
	return file_applewloc_proto_rawDescData
}

var file_applewloc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_applewloc_proto_goTypes = []any{
	(*WifiDevice)(nil),          // 0: main.WifiDevice
	(*AppleWLoc)(nil),           // 1: main.AppleWLoc
	(*WifiDevice_Location)(nil), // 2: main.WifiDevice.Location
}
var file_applewloc_proto_depIdxs = []int32{
	2, // 0: main.WifiDevice.location:type_name -> main.WifiDevice.Location
	0, // 1: main.AppleWLoc.wifi_devices:type_name -> main.WifiDevice
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_applewloc_proto_init() }
func file_applewloc_proto_init() {
	if File_applewloc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_applewloc_proto_rawDesc), len(file_applewloc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_applewloc_proto_goTypes,
		DependencyIndexes: file_applewloc_proto_depIdxs,
		MessageInfos:      file_applewloc_proto_msgTypes,
	}.Build()
	File_applewloc_proto = out.File
	file_applewloc_proto_goTypes = nil
	file_applewloc_proto_depIdxs = nil
}
